### PR TITLE
Use build-in restart to prevent downtime.

### PR DESCRIPTION
**Pull request by lulalalalistia**
Puma will use hot restart when applicable.
https://github.com/puma/puma#normal-vs-hot-vs-phased-restart

### CODE REVIEW

**Comment by lulalala** [comment]
just wondering if you thought this is good or there is other considerations?

**Comment by sandelius** [comment]
I just haven't had time to try it out yet. Will do it the next couple of days.

**Comment by svoboda-jan** [comment]
One issue I see with this change is that the server won't be started if it is restarted for the first time (first deploy calling `puma:restart `) or when the previous deploy failed to start.

I'd suggest something like:

```ruby
desc 'Restart puma'
task restart: :environment do
  if File.exist?(puma_state)
    queue! %[
      cd #{deploy_to}/#{current_path} && #{pumactl_cmd} -S #{puma_state} restart
    ]
  else
    queue! %[ echo 'Puma is not running, starting new instance...'; ]
    invoke :'puma:start'
  end
end
```

I'd check `puma_state` instead of `pumactl_socket`, since that is what `pumactl` relies on.

Also, when reviewing the current implementation I noticed few things:

- It uses `pumactl` and `puma` commands, I'd unify it and use `pumactl`
- When the server is started using a config file, it is not possible to stop it unless the config file specifies a state file with the same path `mina-puma` expects. Here I'd suggest always start specifying the state file, even if using a config file, because that is a reuirement for `pumactl`.
- The `--control ` server should be optional since it is not really required (the state file can be checked for presence of running puma)
- When doing `phased_restart `, I'd also try to `invoke :'puma:start'` if it's not running (same reasons as above)

**Comment by sandelius** [comment]
@svoboda-jan Good points. The reason it mixes `pumactl` and `puma` commands is that when this gem started `pumctl` had a lot of bugs in it.

`pumactl` is definitely the way to go.

@svoboda-jan Could you create a pull request with your suggestions?

**Comment by lulalalalistia** [comment]
@svoboda-jan that's so insightful! Cheers. I just started using puma so I can't say much here. I definitely look forward to your PR :D, and I think I'll close this one as now.

**Comment by lulalala** [comment]
@svoboda-jan if you don't have time, do you mind if I make a PR based on your code? Cheers

**Pull request closed without merging**
